; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D5D012FD-1B1B-4645-B2D5-FBEB6A38A202}
AppName=Workflow
AppVersion=0.3-1
;AppVerName={cm:NameAndVersion,Workflow,0.3-1}
AppPublisher=Cube Inc.
AppPublisherURL=https://cube.new.in/
AppSupportURL=https://cube.new.in/
AppUpdatesURL=https://cube.new.in/
DefaultDirName={autopf}\Workflow
UninstallDisplayIcon={app}\main.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
LicenseFile=D:\Projects\VSCode\wot\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\Admin\Documents\Archive\BFS-Basic File Server\.public
OutputBaseFilename=wot-installer.0.3
SetupIconFile=D:\Projects\VSCode\wot\src\icons\brutus.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Projects\VSCode\wot\dist\main\main.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\VSCode\wot\dist\main\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{autoprograms}\Workflow"; Filename: "{app}\main.exe"
Name: "{autodesktop}\Workflow"; Filename: "{app}\main.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\main.exe"; Description: "{cm:LaunchProgram,Workflow}"; Flags: nowait postinstall skipifsilent

